import { BASE_TYPES } from './baseTypes';

export const QUEUE_DATA_LOADING = `QUEUE_DATA_${BASE_TYPES.LOADING}`;
export const QUEUE_DATA_SUCCESS = `QUEUE_DATA_${BASE_TYPES.SUCCESS}`;
export const QUEUE_DATA_ERROR = `QUEUE_DATA_${BASE_TYPES.ERROR}`;

export const JOIN_QUEUE_LOADING = `JOIN_QUEUE_${BASE_TYPES.LOADING}`;
export const JOIN_QUEUE_SUCCESS = `JOIN_QUEUE_${BASE_TYPES.SUCCESS}`;
export const JOIN_QUEUE_ERROR = `JOIN_QUEUE_${BASE_TYPES.ERROR}`;
